dist: trusty
language: python

addons:
  firefox: "latest"

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"    

env:
  global:
    - "JDK=oracle8"

jdk:
  - oraclejdk8

install:
  - "sudo apt-get install -y oracle-java8-installer phantomjs libmozjs-24-bin"
  - "sudo ln -s /usr/bin/js24 /usr/bin/js"
  - "./install_development.sh"
  - "python setup.py install"

script:
  - "jjs -v < /dev/null"
  - "js --help"
  - "node --version && node --help"
  - "python -m execjs --print-available-runtimes"
  - "python setup.py test"
